create table users(
 id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL primary key ,
 user_name VARCHAR(255) ,
 password  VARCHAR(255) ,
 role_id BIGINT ,
 updated_at timestamp not null ,
 deleted_at  timestamp not null ,
 created_at  timestamp not null ,
 is_active  CHAR(1) ,
 status   CHAR(1)

);