create table members(
    id BIGINT generated by default AS IDENTITY NOT NULL PRIMARY KEY ,
    member_code varchar(255) ,
    member_name varchar(255),
    phone_number numeric,
    address  varchar(255),
    joining_date DATE,
    updated_at timestamp not null ,
    deleted_at  timestamp not null ,
    created_at  timestamp not null ,
    is_active  CHAR(1) ,
    status   CHAR(1)

);