create table roles(
    id  BIGINT generated by default as identity primary key ,
    role_name varchar(255),
    updated_at timestamp not null ,
    deleted_at  timestamp not null ,
    created_at  timestamp not null ,
    is_active  CHAR(1) ,
    status   CHAR(1)
);